// Generated by https://quicktype.io
export interface LinkItems {
  title: string;
  icon: string;
}
export interface UserRecord {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  mobile: string;
  facebook_id: string;
  verified: boolean;
  roleable_type: string;
  roleable_id: number;
  role: string;
  city: string;
  country: string;
  inbox_name: string;
  profession: string;
  buy_art: null;
  preference_range: null;
  newsletter: boolean;
  auth_token: string;
  id_verification_status: string;
  info_verified: boolean;
  interested_in: any[];
}

// Generated by https://quicktype.io

export interface GalleryInfo {
  success: boolean;
  data: Data;
  code: string;
  error: null;
}

export interface Data {
  user: User;
  gallery: Gallery;
  art_categories: ArtCategory[];
  art_descriptions: ArtCategory[];
  art_framed: ArtCategory[];
  art_orientations: ArtCategory[];
  art_signed: ArtCategory[];
  art_sizes: ArtCategory[];
  art_themes: ArtCategory[];
  art_colors: ArtColor[];
  regions: ArtCategory[];
  countries: Country[];
}

export interface ArtCategory {
  id: number;
  name: string;
}

export interface ArtColor {
  id: number;
  name: string;
  image: Image;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface Country {
  id: number;
  name: string;
  region_id: number | null;
}

export interface Gallery {
  id: number;
  title: string;
  city: string;
  country: string;
  link: string;
  description: string;
  email: string;
  image: Image;
  artists: number;
  artworks: Artworks;
  shows: number;
  analytics: Analytics;
  dashboard_analytics: DashboardAnalytics;
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ByCountry {
  name: string;
  value: number;
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artworks {
  total: number;
  live: number;
  for_sale: number;
  pending: number;
}

export interface DashboardAnalytics {
  artists: AnalyticsData[];
  artworks: AnalyticsData[];
  countries: AnalyticsData[];
}

export interface AnalyticsData {
  id: number;
  image?: string;
  name: string;
  view_count: number;
  percentage: number;
}

export interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  mobile: string;
  facebook_id: string;
  verified: boolean;
  roleable_type: string;
  roleable_id: number;
  role: string;
  city: string | null;
  country: string | null;
  inbox_name: string;
  profession: string | null;
  buy_art: null;
  preference_range: null;
  newsletter: boolean;
  auth_token: string;
  id_verification_status: string;
  info_verified: boolean;
  interested_in: any[];
}

// Generated by https://quicktype.io

export interface Artists {
  success: boolean;
  data: Data;
  code: string;
  error: null;
}

export interface Data {
  items: ArtistItem[];
  current_count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface ArtistItem {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean | null;
  region_id: number;
  country_id: number;
  image: Image;
  cv_file: null;
  full_name: string;
  artworks: Artworks;
  analytics: Analytics;
  likes_analytics: LikesAnalytics;
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ByCountry {
  name: string;
  value: number;
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artworks {
  total: number;
  live: number;
  pending: number;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface LikesAnalytics {
  total_count: number;
}

// Generated by https://quicktype.io

export interface ArtworksRecord {
  id: number;
  title: string;
  slug: string;
  price: string;
  is_in_stock: boolean;
  price_text: string;
  year_range: null | string;
  active: boolean;
  quantity: number;
  buyer_premium: boolean;
  art_description: number;
  image: Image;
  artist: Artist;
  analytics: Analytics;
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ByCountry {
  name: string | Name;
  value: number;
}

export enum Name {
  Angola = 'Angola',
  Armenia = 'Armenia',
  Australia = 'Australia',
  Austria = 'Austria',
  Bahrain = 'Bahrain',
  Bangladesh = 'Bangladesh',
  Belgium = 'Belgium',
  BosniaAndHerzegovina = 'Bosnia and Herzegovina',
  Brazil = 'Brazil',
  Bulgaria = 'Bulgaria',
  Canada = 'Canada',
  Chile = 'Chile',
  China = 'China',
  Cyprus = 'Cyprus',
  Czechia = 'Czechia',
  Denmark = 'Denmark',
  Egypt = 'Egypt',
  Empty = '',
  EquatorialGuinea = 'Equatorial Guinea',
  Finland = 'Finland',
  France = 'France',
  Georgia = 'Georgia',
  Germany = 'Germany',
  Greece = 'Greece',
  Guernsey = 'Guernsey',
  HongKong = 'Hong Kong',
  Iceland = 'Iceland',
  India = 'India',
  Iran = 'Iran',
  Iraq = 'Iraq',
  Ireland = 'Ireland',
  Italy = 'Italy',
  Japan = 'Japan',
  Jordan = 'Jordan',
  Kazakhstan = 'Kazakhstan',
  Kuwait = 'Kuwait',
  Lebanon = 'Lebanon',
  Luxembourg = 'Luxembourg',
  Malaysia = 'Malaysia',
  Moldova = 'Moldova',
  Morocco = 'Morocco',
  Netherlands = 'Netherlands',
  Norway = 'Norway',
  Oman = 'Oman',
  Pakistan = 'Pakistan',
  PalestinianTerritory = 'Palestinian Territory',
  Poland = 'Poland',
  PuertoRico = 'Puerto Rico',
  Qatar = 'Qatar',
  Romania = 'Romania',
  Russia = 'Russia',
  SaudiArabia = 'Saudi Arabia',
  Serbia = 'Serbia',
  Singapore = 'Singapore',
  SouthAfrica = 'South Africa',
  SouthKorea = 'South Korea',
  Spain = 'Spain',
  Sweden = 'Sweden',
  Switzerland = 'Switzerland',
  Syria = 'Syria',
  Thailand = 'Thailand',
  Tunisia = 'Tunisia',
  Turkey = 'Turkey',
  Ukraine = 'Ukraine',
  UnitedArabEmirates = 'United Arab Emirates',
  UnitedKingdom = 'United Kingdom',
  UnitedStates = 'United States',
  Vietnam = 'Vietnam',
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artist {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  region_id: number;
  country_id: number;
  image: Image;
  cv_file: null;
  full_name: string;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

// Generated by https://quicktype.io

export interface Conversations {
  items: ConversationItem[];
  current_count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface ConversationItem {
  id: number;
  created_at: string;
  updated_at: string;
  title: string;
  html_title: string;
  first_participant: FirstParticipant;
  second_participant: SecondParticipant;
  artwork: Artwork | null;
  last_message: LastMessage;
}

export interface Artwork {
  id: number;
  title: string;
  slug: string;
  price: string;
  is_in_stock: boolean;
  price_text: string;
  year_range: string;
  active: boolean;
  quantity: number;
  buyer_premium: boolean;
  description: string;
  image: Image;
  artist: Artist;
  size: string;
  art_categories: string[];
}

export interface Artist {
  id: number;
  slug: string;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  full_name: string;
  image: Image;
  cv_file: null;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface FirstParticipant {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  mobile: string;
  facebook_id: null;
  verified: boolean;
  roleable_type: string;
  roleable_id: null;
  role: string;
  city: string;
  country: string;
  inbox_name: string;
}

export interface LastMessage {
  id: number;
  participant_type: string;
  participant_id: number;
  viewed_at: null;
  created_at: string;
  updated_at: string;
  message: string;
  participant: Participant;
  attachments: any[];
}

export interface Participant {
  id: number;
  title?: string;
  slug?: string;
  city: string;
  country: string;
  link?: string;
  description?: string;
  email: string;
  inbox_name: string;
  image?: Image;
  first_name?: string;
  last_name?: string;
  mobile?: string;
  facebook_id?: null;
  verified?: boolean;
  roleable_type?: null | string;
  roleable_id?: null;
  role?: string;
}

export interface SecondParticipant {
  id: number;
  title: string;
  slug: string;
  city: string;
  country: string;
  link: string;
  description: string;
  email: string;
  inbox_name: string;
  image: Image;
}

// Generated by https://quicktype.io

export interface GallerySystemArtists {
  success: boolean;
  data: GallerySystemData;
  code: string;
  error: null;
}

export interface GallerySystemData {
  items: GallerySystemArtist[];
  current_count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface GallerySystemArtist {
  id: number;
  first_name: string;
  last_name: null | string;
  is_featured: boolean | null;
  region_id: number | null;
  country_id: number | null;
  image: Image | null;
  cv_file: CvFile | null;
  full_name: string;
}

export interface CvFile {
  original: string;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

// Generated by https://quicktype.io

export interface SingleArtist {
  success: boolean;
  data: SingleArtistData;
  code: string;
  error: null;
}

export interface SingleArtistData {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  region_id: number;
  country_id: number;
  image: Image;
  cv_file: null;
  full_name: string;
  artworks: Artworks;
  analytics: Analytics;
  likes_analytics: LikesAnalytics;
  about: string;
  website: string;
  articles: Article[];
  key_collections: KeyCollection[];
  selected_exhibitions: SelectedExhibition[];
}

export type Article = {
  title: string;
  url: string;
};

export interface KeyCollection {
  date: string;
  museum_name: string;
  city: string;
  country_id: number;
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ByCountry {
  name: string;
  value: number;
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artworks {
  total: number;
  live: number;
  pending: number;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface LikesAnalytics {
  total_count: number;
}

export interface SelectedExhibition {
  id?: number;
  title: string;
  date: string;
  exhibition_type: string;
  location: string;
  city: string;
  country_id: number;
}

// Generated by https://quicktype.io

export interface SingleArtwork {
  success: boolean;
  data: SingleArtworkData;
  code: string;
  error: null;
}

export interface SingleArtworkData {
  id: number;
  title: string;
  slug: string;
  price: string;
  is_in_stock: boolean;
  price_text: string;
  year_range: string;
  active: boolean;
  quantity: string | number;
  buyer_premium: boolean;
  art_description: number;
  image: Image;
  artist: Artist;
  analytics: Analytics;
  height: string;
  width: string;
  length: string | null;
  depth: string | null;
  weight: string | null;
  details: string;
  shipping: string;
  edition_of: string | null;
  provenance: string | null;
  condition_report: string;
  location: string;
  is_for_charity: boolean;
  attachments: Attachment[];
  edition: string | null;
  artwork_details: string;
  size: string;
  signed: number;
  framed: number;
  region: number;
  country: number;
  art_size: number;
  art_orientation: number;
  art_categories: number[];
  art_colors: number[];
  art_themes: number[];
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ByCountry {
  name: string;
  value: number;
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artist {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  region_id: number;
  country_id: number;
  image: Image;
  cv_file: null;
  full_name: string;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface Attachment {
  id: number;
  file_file_name: string;
  file_content_type: string;
  sort_order: number;
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

// Generated by https://quicktype.io

export interface ArtistInfo {
  success: boolean;
  data: ArtistInfoData;
  code: string;
  error: null;
}

export interface ArtistInfoData {
  user: User;
  artist: ThisArtist;
  art_categories: ArtCategory[];
  art_descriptions: ArtCategory[];
  art_framed: ArtCategory[];
  art_orientations: ArtCategory[];
  art_signed: ArtCategory[];
  art_sizes: ArtCategory[];
  art_themes: ArtCategory[];
  art_colors: ArtColor[];
  regions: ArtCategory[];
  countries: Country[];
}

export interface ArtCategory {
  id: number;
  name: string;
}

export interface ArtColor {
  id: number;
  name: string;
  image: Image;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface ThisArtist {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean | null;
  region_id: number;
  country_id: number;
  full_name: string;
  artworks: Artworks;
  analytics: Analytics;
  likes_analytics: LikesAnalytics;
  dashboard_analytics: DashboardAnalytics;
  image: Image;
  cv_file: null;
  about: null;
  website: null;
  articles: any[];
  key_collections: any[];
  selected_exhibitions: any[];
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artworks {
  total: number;
  live: number;
  pending: number;
}

export interface DashboardAnalytics {
  artists: AnalyticsData[];
  artworks: AnalyticsData[];
  countries: AnalyticsData[];
}

export interface LikesAnalytics {
  total_count: number;
}

export interface Country {
  id: number;
  name: string;
  region_id: number | null;
}

export interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  mobile: string;
  facebook_id: string;
  verified: boolean;
  roleable_type: string;
  roleable_id: number;
  role: string;
  city: null | string;
  country: string | null;
  inbox_name: string;
  profession: string | null;
  buy_art: null;
  preference_range: null;
  newsletter: boolean;
  auth_token: string;
  id_verification_status: string;
  info_verified: boolean;
  interested_in: any[];
}

declare global {
  interface Window {
    authStore: any; // 👈️ turn off type checking
  }
}

// Generated by https://quicktype.io

export interface ArtistArtworks {
  success: boolean;
  data: ArtistArtworksData;
  code: string;
  error: null;
}

export interface ArtistArtworksData {
  items: ArtistArtworksDataItem[];
  current_count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface ArtistArtworksDataItem {
  id: number;
  title: string;
  slug: string;
  price: null | string;
  is_in_stock: boolean;
  price_text: string;
  year_range: null | string;
  active: boolean;
  quantity: number;
  buyer_premium: boolean;
  art_description: number;
  image: Image;
  artist: Artist;
  analytics: Analytics;
}

export interface Analytics {
  views: Views;
}

export interface Views {
  all_time: AllTime;
  monthly: Monthly[];
}

export interface AllTime {
  total_views: number;
  logged_in_users: number;
  anonymous_users: number;
  by_country: ByCountry[];
}

export interface ArtistArtworksByCountry {
  name: Name;
  value: number;
}

export enum ArtistArtworksByCountryName {
  Aruba = 'Aruba',
  Australia = 'Australia',
  Austria = 'Austria',
  Azerbaijan = 'Azerbaijan',
  Bahrain = 'Bahrain',
  Belgium = 'Belgium',
  Brazil = 'Brazil',
  Canada = 'Canada',
  China = 'China',
  Cyprus = 'Cyprus',
  Czechia = 'Czechia',
  Egypt = 'Egypt',
  Empty = '',
  Finland = 'Finland',
  France = 'France',
  Gabon = 'Gabon',
  Germany = 'Germany',
  Greece = 'Greece',
  HongKong = 'Hong Kong',
  India = 'India',
  Ireland = 'Ireland',
  Italy = 'Italy',
  Jordan = 'Jordan',
  Kuwait = 'Kuwait',
  Lebanon = 'Lebanon',
  Mauritius = 'Mauritius',
  Mexico = 'Mexico',
  Moldova = 'Moldova',
  Nepal = 'Nepal',
  Netherlands = 'Netherlands',
  Norway = 'Norway',
  Palestine = 'Palestine',
  PalestinianTerritory = 'Palestinian Territory',
  Philippines = 'Philippines',
  Poland = 'Poland',
  Portugal = 'Portugal',
  Qatar = 'Qatar',
  Romania = 'Romania',
  Russia = 'Russia',
  SaudiArabia = 'Saudi Arabia',
  Seychelles = 'Seychelles',
  Singapore = 'Singapore',
  SouthAfrica = 'South Africa',
  SouthKorea = 'South Korea',
  Spain = 'Spain',
  Sweden = 'Sweden',
  Switzerland = 'Switzerland',
  Taiwan = 'Taiwan',
  Turkey = 'Turkey',
  Ukraine = 'Ukraine',
  UnitedArabEmirates = 'United Arab Emirates',
  UnitedKingdom = 'United Kingdom',
  UnitedStates = 'United States',
}

export interface Monthly {
  month: string;
  year: string;
  data: AllTime;
}

export interface Artist {
  id: number;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  region_id: number;
  country_id: number;
  full_name: string;
  image: Image;
  cv_file: null;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export type FormData = {
  first_name: string;
  last_name: string;
  about: string;
  website: string;
  region_id: string;
  country_id: string;
  selected_exhibitions: Array<{
    title: string;
    date: string;
    exhibition_type: string;
    location: string;
    city: string;
    country_id: string;
  }>;
  key_collections: Array<{
    date: string;
    museum_name: string;
    city: string;
    country_id: string;
  }>;
  articles: Array<{
    title: string;
    url: string;
  }>;
  image: object;
};

// Generated by https://quicktype.io

export interface Messages {
  success: boolean;
  data: MessagesData;
  code: string;
  error: null;
}

export interface MessagesData {
  id: number;
  created_at: string;
  updated_at: string;
  title: string;
  html_title: string;
  first_participant: FirstParticipant;
  second_participant: SecondParticipantClass;
  artwork: Artwork;
  last_message: TheLastMessage;
  conversation_messages: ConversationMessage[];
}

export interface Artwork {
  id: number;
  title: string;
  slug: string;
  price: string;
  is_in_stock: boolean;
  price_text: string;
  year_range: string;
  active: boolean;
  quantity: number;
  buyer_premium: boolean;
  description: string;
  image: Image;
  artist: Artist;
  size: string;
  art_categories: string[];
}

export interface Artist {
  id: number;
  slug: string;
  first_name: string;
  last_name: string;
  is_featured: boolean;
  full_name: string;
  image: Image;
  cv_file: null;
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}

export interface ConversationMessage {
  id: number;
  participant_type: string;
  participant_id: number;
  viewed_at: null | string;
  created_at: string;
  updated_at: string;
  message: string;
  participant: ConversationMessageParticipant;
  attachments: any[];
}

export interface ConversationMessageParticipant {
  id: number;
  email: string;
  first_name?: string;
  last_name?: string;
  mobile?: string;
  facebook_id?: null;
  verified?: boolean;
  roleable_type?: string;
  roleable_id?: null;
  role?: string;
  city: string;
  country: string;
  inbox_name: string;
  title?: string;
  slug?: string;
  link?: string;
  description?: string;
  image?: Image;
}

export interface FirstParticipant {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  mobile: string;
  facebook_id: null;
  verified: boolean;
  roleable_type: string;
  roleable_id: null;
  role: string;
  city: string;
  country: string;
  inbox_name: string;
}

export interface TheLastMessage {
  id: number;
  participant_type: string;
  participant_id: number;
  viewed_at: null;
  created_at: string;
  updated_at: string;
  message: string;
  participant: SecondParticipantClass;
  attachments: any[];
}

export interface SecondParticipantClass {
  id: number;
  title: string;
  slug: string;
  city: string;
  country: string;
  link: string;
  description: string;
  email: string;
  inbox_name: string;
  image: Image;
}

// Generated by https://quicktype.io

export interface GalleryShows {
  success: boolean;
  data: GalleryShowsData;
  code: string;
  error: null;
}

export interface GalleryShowsData {
  items: GalleryShowsItem[];
  current_count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface GalleryShowsItem {
  id: number;
  title: string;
  description: string;
  date_from: string;
  date_to: string;
  curated_by: string;
  active: boolean;
  image: Image;
  formatted_date: string;
  artworks: Artwork[];
}

export interface Image {
  thumbnail: string;
  small: string;
  medium: string;
  large: string;
  original: string;
}
export interface SortOrder {
  id: number;
  order: number;
}
